expected_tree_repr = ("APITree(branches=[APINode(api='companies', layers=[EndpointLayer(path='/companies', "
                      "api_levels=['companies'], parameters=[], next=[], methods=[], _id=UUID("
                      "'f728b4fa-4248-5e3a-0a5d-2f346baa9455')), EndpointLayer(path='/companies/{company_id}', "
                      "api_levels=['companies'], parameters=[EndpointParameter(name='company_id', in_location='path', "
                      "type='string', required=True, format='')], next=[APINode(api='employees', "
                      "layers=[EndpointLayer(path='/employees', api_levels=['employees'], parameters=[], next=[], "
                      "methods=[], _id=UUID('b4862b21-fb97-d435-8856-1712e8e5216a')), EndpointLayer("
                      "path='/employees/{employee_num}', api_levels=['employees'], parameters=[EndpointParameter("
                      "name='employee_num', in_location='path', type='string', required=True, format='')], next=[], "
                      "methods=[], _id=UUID('5487ce1e-af19-922a-d9b8-a714e61a441c'))], next=APITree(branches=[]), "
                      "_id=UUID('17e0aa3c-0398-3ca8-ea7e-9d498c778ea6')), APINode(api='departments', "
                      "layers=[EndpointLayer(path='/departments/{department_name}', api_levels=['departments'], "
                      "parameters=[EndpointParameter(name='department_name', in_location='path', type='string', "
                      "required=True, format='')], next=[APINode(api='employees', layers=[EndpointLayer("
                      "path='/employees', api_levels=['employees'], parameters=[], next=[], methods=[], "
                      "_id=UUID('b4862b21-fb97-d435-8856-1712e8e5216a')), EndpointLayer(path='/employees/{"
                      "employee_num}', api_levels=['employees'], parameters=[EndpointParameter(name='employee_num', "
                      "in_location='path', type='string', required=True, format='')], next=[], methods=[], "
                      "_id=UUID('5487ce1e-af19-922a-d9b8-a714e61a441c'))], next=APITree(branches=[]), "
                      "_id=UUID('17e0aa3c-0398-3ca8-ea7e-9d498c778ea6'))], methods=[], _id=UUID("
                      "'8d723104-f773-83c1-3458-a748e9bb17bc'))], next=APITree(branches=[APINode(api='employees', "
                      "layers=[EndpointLayer(path='/employees', api_levels=['employees'], parameters=[], next=[], "
                      "methods=[], _id=UUID('b4862b21-fb97-d435-8856-1712e8e5216a')), EndpointLayer("
                      "path='/employees/{employee_num}', api_levels=['employees'], parameters=[EndpointParameter("
                      "name='employee_num', in_location='path', type='string', required=True, format='')], next=[], "
                      "methods=[], _id=UUID('5487ce1e-af19-922a-d9b8-a714e61a441c'))], next=APITree(branches=[]), "
                      "_id=UUID('17e0aa3c-0398-3ca8-ea7e-9d498c778ea6'))]), _id=UUID("
                      "'b5d32b16-6619-4cb1-d710-37d1b83e90ec'))], methods=[], _id=UUID("
                      "'f7c1bd87-4da5-e709-d471-3d60c8a70639')), EndpointLayer(path='/companies/{company_id}/{"
                      "number}', api_levels=['companies'], parameters=[EndpointParameter(name='company_id', "
                      "in_location='path', type='string', required=True, format=''), EndpointParameter(name='number', "
                      "in_location='path', type='string', required=True, format='')], next=[], methods=[], "
                      "_id=UUID('23a7711a-8133-2876-37eb-dcd9e87a1613'))], next=APITree(branches=[APINode("
                      "api='employees', layers=[EndpointLayer(path='/employees', api_levels=['employees'], "
                      "parameters=[], next=[], methods=[], _id=UUID('b4862b21-fb97-d435-8856-1712e8e5216a')), "
                      "EndpointLayer(path='/employees/{employee_num}', api_levels=['employees'], parameters=["
                      "EndpointParameter(name='employee_num', in_location='path', type='string', required=True, "
                      "format='')], next=[], methods=[], _id=UUID('5487ce1e-af19-922a-d9b8-a714e61a441c'))], "
                      "next=APITree(branches=[]), _id=UUID('17e0aa3c-0398-3ca8-ea7e-9d498c778ea6')), "
                      "APINode(api='departments', layers=[EndpointLayer(path='/departments/{department_name}', "
                      "api_levels=['departments'], parameters=[EndpointParameter(name='department_name', "
                      "in_location='path', type='string', required=True, format='')], next=[APINode(api='employees', "
                      "layers=[EndpointLayer(path='/employees', api_levels=['employees'], parameters=[], next=[], "
                      "methods=[], _id=UUID('b4862b21-fb97-d435-8856-1712e8e5216a')), EndpointLayer("
                      "path='/employees/{employee_num}', api_levels=['employees'], parameters=[EndpointParameter("
                      "name='employee_num', in_location='path', type='string', required=True, format='')], next=[], "
                      "methods=[], _id=UUID('5487ce1e-af19-922a-d9b8-a714e61a441c'))], next=APITree(branches=[]), "
                      "_id=UUID('17e0aa3c-0398-3ca8-ea7e-9d498c778ea6'))], methods=[], _id=UUID("
                      "'8d723104-f773-83c1-3458-a748e9bb17bc'))], next=APITree(branches=[APINode(api='employees', "
                      "layers=[EndpointLayer(path='/employees', api_levels=['employees'], parameters=[], next=[], "
                      "methods=[], _id=UUID('b4862b21-fb97-d435-8856-1712e8e5216a')), EndpointLayer("
                      "path='/employees/{employee_num}', api_levels=['employees'], parameters=[EndpointParameter("
                      "name='employee_num', in_location='path', type='string', required=True, format='')], next=[], "
                      "methods=[], _id=UUID('5487ce1e-af19-922a-d9b8-a714e61a441c'))], next=APITree(branches=[]), "
                      "_id=UUID('17e0aa3c-0398-3ca8-ea7e-9d498c778ea6'))]), _id=UUID("
                      "'b5d32b16-6619-4cb1-d710-37d1b83e90ec'))]), _id=UUID('eb2083e6-ce16-4dba-0ff1-8e0242af9fc3'))])")
