expected_tree_repr = ("APITree(branches=[APINode(api='companies', "
                      "layers=[EndpointLayer(path='/companies', api_levels=['companies'], "
                      "parameters=[], next=[], methods=[EndpointMethod(name='post', "
                      "description='Creates a new Company and expands your capitalist empire.', "
                      "parameters=[], request_schemas=[ContentSchema(name='CompanyCreate', "
                      "content_type='application/json', definition={'title': 'Company Creation "
                      "Request', 'type': 'object', 'allOf': [{'$ref': "
                      "'#/components/schemas/CompanyBase'}]}, code=0)], "
                      "response_schemas=[ContentSchema(name='Company', "
                      "content_type='application/json', definition={'title': 'Company', 'type': "
                      "'object', 'allOf': [{'$ref': '#/components/schemas/CompanyBase'}, {'type': "
                      "'object', 'properties': {'created': {'type': 'string', 'format': "
                      "'date-time', 'example': '2023-06-19T21:00:00Z'}, 'modified': {'type': "
                      "'string', 'format': 'date-time', 'example': '2023-06-19T21:00:00Z'}}}]}, "
                      "code=201), ContentSchema(name='ErrorResponse', "
                      "content_type='application/json', definition={'title': 'Error Response', "
                      "'type': 'object', 'required': ['status', 'message'], 'properties': "
                      "{'status': {'type': 'integer', 'example': 400}, 'message': {'type': "
                      "'string', 'example': 'Oh, no!'}}}, code=400)]), EndpointMethod(name='get', "
                      "description='Returns all your companies.', "
                      "parameters=[EndpointParameter(name='name', in_location='query', "
                      "type='string', required=False, format='')], request_schemas=[], "
                      "response_schemas=[ContentSchema(name='CompanyList', "
                      "content_type='application/json', definition={'title': 'Company List', "
                      "'type': 'array', 'items': {'$ref': '#/components/schemas/Company'}}, "
                      "code=200)])], _id=UUID('f728b4fa-4248-5e3a-0a5d-2f346baa9455')), "
                      "EndpointLayer(path='/companies/{company_id}', api_levels=['companies'], "
                      "parameters=[EndpointParameter(name='company_id', in_location='path', "
                      "type='string', required=True, format='')], next=[APINode(api='employees', "
                      "layers=[EndpointLayer(path='/employees', api_levels=['employees'], "
                      "parameters=[], next=[], methods=[EndpointMethod(name='post', "
                      "description='Hires a new employee!', "
                      "parameters=[EndpointParameter(name='company_id', in_location='path', "
                      "type='string', required=True, format='')], "
                      "request_schemas=[ContentSchema(name='EmployeeCreate', "
                      "content_type='application/json', definition={'title': 'Employee Create "
                      "Request', 'type': 'object', 'allOf': [{'$ref': "
                      "'#/components/schemas/EmployeeBase'}]}, code=0)], "
                      "response_schemas=[ContentSchema(name='Employee', "
                      "content_type='application/json', definition={'title': 'Employee', 'type': "
                      "'object', 'allOf': [{'$ref': '#/components/schemas/EmployeeBase'}]}, "
                      "code=201)]), EndpointMethod(name='get', description='Returns all your "
                      "employees.', parameters=[EndpointParameter(name='company_id', "
                      "in_location='path', type='string', required=True, format='')], "
                      "request_schemas=[], response_schemas=[ContentSchema(name='EmployeeList', "
                      "content_type='application/json', definition={'title': 'Employee List', "
                      "'type': 'array', 'items': {'$ref': '#/components/schemas/Employee'}}, "
                      "code=200)])], _id=UUID('b4862b21-fb97-d435-8856-1712e8e5216a')), "
                      "EndpointLayer(path='/employees/{employee_num}', api_levels=['employees'], "
                      "parameters=[EndpointParameter(name='employee_num', in_location='path', "
                      "type='string', required=True, format='')], next=[], "
                      "methods=[EndpointMethod(name='get', description='Returns one of your company "
                      "employees', parameters=[EndpointParameter(name='company_id', "
                      "in_location='path', type='string', required=True, format=''), "
                      "EndpointParameter(name='employee_num', in_location='path', type='integer', "
                      "required=True, format='')], request_schemas=[], "
                      "response_schemas=[ContentSchema(name='Employee', "
                      "content_type='application/json', definition={'title': 'Employee', 'type': "
                      "'object', 'allOf': [{'$ref': '#/components/schemas/EmployeeBase'}]}, "
                      "code=200)])], _id=UUID('5487ce1e-af19-922a-d9b8-a714e61a441c'))], "
                      'next=APITree(branches=[]), '
                      "_id=UUID('17e0aa3c-0398-3ca8-ea7e-9d498c778ea6')), "
                      "APINode(api='departments', "
                      "layers=[EndpointLayer(path='/departments/{department_name}', "
                      "api_levels=['departments'], "
                      "parameters=[EndpointParameter(name='department_name', in_location='path', "
                      "type='string', required=True, format='')], next=[APINode(api='employees', "
                      "layers=[EndpointLayer(path='/employees', api_levels=['employees'], "
                      "parameters=[], next=[], methods=[EndpointMethod(name='post', "
                      "description='Hires a new employee!', "
                      "parameters=[EndpointParameter(name='company_id', in_location='path', "
                      "type='string', required=True, format='')], "
                      "request_schemas=[ContentSchema(name='EmployeeCreate', "
                      "content_type='application/json', definition={'title': 'Employee Create "
                      "Request', 'type': 'object', 'allOf': [{'$ref': "
                      "'#/components/schemas/EmployeeBase'}]}, code=0)], "
                      "response_schemas=[ContentSchema(name='Employee', "
                      "content_type='application/json', definition={'title': 'Employee', 'type': "
                      "'object', 'allOf': [{'$ref': '#/components/schemas/EmployeeBase'}]}, "
                      "code=201)]), EndpointMethod(name='get', description='Returns all your "
                      "employees.', parameters=[EndpointParameter(name='company_id', "
                      "in_location='path', type='string', required=True, format='')], "
                      "request_schemas=[], response_schemas=[ContentSchema(name='EmployeeList', "
                      "content_type='application/json', definition={'title': 'Employee List', "
                      "'type': 'array', 'items': {'$ref': '#/components/schemas/Employee'}}, "
                      "code=200)])], _id=UUID('b4862b21-fb97-d435-8856-1712e8e5216a')), "
                      "EndpointLayer(path='/employees/{employee_num}', api_levels=['employees'], "
                      "parameters=[EndpointParameter(name='employee_num', in_location='path', "
                      "type='string', required=True, format='')], next=[], "
                      "methods=[EndpointMethod(name='get', description='Returns one of your company "
                      "employees', parameters=[EndpointParameter(name='company_id', "
                      "in_location='path', type='string', required=True, format=''), "
                      "EndpointParameter(name='employee_num', in_location='path', type='integer', "
                      "required=True, format='')], request_schemas=[], "
                      "response_schemas=[ContentSchema(name='Employee', "
                      "content_type='application/json', definition={'title': 'Employee', 'type': "
                      "'object', 'allOf': [{'$ref': '#/components/schemas/EmployeeBase'}]}, "
                      "code=200)])], _id=UUID('5487ce1e-af19-922a-d9b8-a714e61a441c'))], "
                      'next=APITree(branches=[]), '
                      "_id=UUID('17e0aa3c-0398-3ca8-ea7e-9d498c778ea6'))], methods=[], "
                      "_id=UUID('8d723104-f773-83c1-3458-a748e9bb17bc'))], "
                      "next=APITree(branches=[APINode(api='employees', "
                      "layers=[EndpointLayer(path='/employees', api_levels=['employees'], "
                      "parameters=[], next=[], methods=[EndpointMethod(name='post', "
                      "description='Hires a new employee!', "
                      "parameters=[EndpointParameter(name='company_id', in_location='path', "
                      "type='string', required=True, format='')], "
                      "request_schemas=[ContentSchema(name='EmployeeCreate', "
                      "content_type='application/json', definition={'title': 'Employee Create "
                      "Request', 'type': 'object', 'allOf': [{'$ref': "
                      "'#/components/schemas/EmployeeBase'}]}, code=0)], "
                      "response_schemas=[ContentSchema(name='Employee', "
                      "content_type='application/json', definition={'title': 'Employee', 'type': "
                      "'object', 'allOf': [{'$ref': '#/components/schemas/EmployeeBase'}]}, "
                      "code=201)]), EndpointMethod(name='get', description='Returns all your "
                      "employees.', parameters=[EndpointParameter(name='company_id', "
                      "in_location='path', type='string', required=True, format='')], "
                      "request_schemas=[], response_schemas=[ContentSchema(name='EmployeeList', "
                      "content_type='application/json', definition={'title': 'Employee List', "
                      "'type': 'array', 'items': {'$ref': '#/components/schemas/Employee'}}, "
                      "code=200)])], _id=UUID('b4862b21-fb97-d435-8856-1712e8e5216a')), "
                      "EndpointLayer(path='/employees/{employee_num}', api_levels=['employees'], "
                      "parameters=[EndpointParameter(name='employee_num', in_location='path', "
                      "type='string', required=True, format='')], next=[], "
                      "methods=[EndpointMethod(name='get', description='Returns one of your company "
                      "employees', parameters=[EndpointParameter(name='company_id', "
                      "in_location='path', type='string', required=True, format=''), "
                      "EndpointParameter(name='employee_num', in_location='path', type='integer', "
                      "required=True, format='')], request_schemas=[], "
                      "response_schemas=[ContentSchema(name='Employee', "
                      "content_type='application/json', definition={'title': 'Employee', 'type': "
                      "'object', 'allOf': [{'$ref': '#/components/schemas/EmployeeBase'}]}, "
                      "code=200)])], _id=UUID('5487ce1e-af19-922a-d9b8-a714e61a441c'))], "
                      'next=APITree(branches=[]), '
                      "_id=UUID('17e0aa3c-0398-3ca8-ea7e-9d498c778ea6'))]), "
                      "_id=UUID('b5d32b16-6619-4cb1-d710-37d1b83e90ec'))], "
                      "methods=[EndpointMethod(name='get', description='Returns a company by its "
                      "ID.', parameters=[EndpointParameter(name='company_id', in_location='path', "
                      "type='string', required=True, format='')], request_schemas=[], "
                      "response_schemas=[ContentSchema(name='Company', "
                      "content_type='application/json', definition={'title': 'Company', 'type': "
                      "'object', 'allOf': [{'$ref': '#/components/schemas/CompanyBase'}, {'type': "
                      "'object', 'properties': {'created': {'type': 'string', 'format': "
                      "'date-time', 'example': '2023-06-19T21:00:00Z'}, 'modified': {'type': "
                      "'string', 'format': 'date-time', 'example': '2023-06-19T21:00:00Z'}}}]}, "
                      "code=200)]), EndpointMethod(name='put', description='Updates an exising "
                      "company.', parameters=[EndpointParameter(name='company_id', "
                      "in_location='path', type='string', required=True, format='')], "
                      "request_schemas=[ContentSchema(name='CompanyUpdate', "
                      "content_type='application/json', definition={'title': 'Company Update "
                      "Request', 'type': 'object', 'allOf': [{'$ref': "
                      "'#/components/schemas/CompanyBase'}]}, code=0)], "
                      "response_schemas=[ContentSchema(name='Company', "
                      "content_type='application/json', definition={'title': 'Company', 'type': "
                      "'object', 'allOf': [{'$ref': '#/components/schemas/CompanyBase'}, {'type': "
                      "'object', 'properties': {'created': {'type': 'string', 'format': "
                      "'date-time', 'example': '2023-06-19T21:00:00Z'}, 'modified': {'type': "
                      "'string', 'format': 'date-time', 'example': '2023-06-19T21:00:00Z'}}}]}, "
                      "code=200)]), EndpointMethod(name='delete', description='Deletes a company "
                      ":(', parameters=[EndpointParameter(name='company_id', in_location='path', "
                      "type='string', required=True, format='')], request_schemas=[], "
                      "response_schemas=[])], _id=UUID('f7c1bd87-4da5-e709-d471-3d60c8a70639')), "
                      "EndpointLayer(path='/companies/{company_id}/{number}', "
                      "api_levels=['companies'], parameters=[EndpointParameter(name='company_id', "
                      "in_location='path', type='string', required=True, format=''), "
                      "EndpointParameter(name='number', in_location='path', type='string', "
                      "required=True, format='')], next=[], methods=[EndpointMethod(name='get', "
                      "description='An endpoint used to test random things.', "
                      "parameters=[EndpointParameter(name='company_id', in_location='path', "
                      "type='string', required=True, format=''), EndpointParameter(name='number', "
                      "in_location='path', type='integer', required=True, format='')], "
                      "request_schemas=[], response_schemas=[ContentSchema(name='Company', "
                      "content_type='application/json', definition={'title': 'Company', 'type': "
                      "'object', 'allOf': [{'$ref': '#/components/schemas/CompanyBase'}, {'type': "
                      "'object', 'properties': {'created': {'type': 'string', 'format': "
                      "'date-time', 'example': '2023-06-19T21:00:00Z'}, 'modified': {'type': "
                      "'string', 'format': 'date-time', 'example': '2023-06-19T21:00:00Z'}}}]}, "
                      "code=200), ContentSchema(name='Company', content_type='application/xml', "
                      "definition={'title': 'Company', 'type': 'object', 'allOf': [{'$ref': "
                      "'#/components/schemas/CompanyBase'}, {'type': 'object', 'properties': "
                      "{'created': {'type': 'string', 'format': 'date-time', 'example': "
                      "'2023-06-19T21:00:00Z'}, 'modified': {'type': 'string', 'format': "
                      "'date-time', 'example': '2023-06-19T21:00:00Z'}}}]}, code=200), "
                      "ContentSchema(name='ErrorResponse', content_type='application/json', "
                      "definition={'title': 'Error Response', 'type': 'object', 'required': "
                      "['status', 'message'], 'properties': {'status': {'type': 'integer', "
                      "'example': 400}, 'message': {'type': 'string', 'example': 'Oh, no!'}}}, "
                      "code=404)])], _id=UUID('23a7711a-8133-2876-37eb-dcd9e87a1613'))], "
                      "next=APITree(branches=[APINode(api='employees', "
                      "layers=[EndpointLayer(path='/employees', api_levels=['employees'], "
                      "parameters=[], next=[], methods=[EndpointMethod(name='post', "
                      "description='Hires a new employee!', "
                      "parameters=[EndpointParameter(name='company_id', in_location='path', "
                      "type='string', required=True, format='')], "
                      "request_schemas=[ContentSchema(name='EmployeeCreate', "
                      "content_type='application/json', definition={'title': 'Employee Create "
                      "Request', 'type': 'object', 'allOf': [{'$ref': "
                      "'#/components/schemas/EmployeeBase'}]}, code=0)], "
                      "response_schemas=[ContentSchema(name='Employee', "
                      "content_type='application/json', definition={'title': 'Employee', 'type': "
                      "'object', 'allOf': [{'$ref': '#/components/schemas/EmployeeBase'}]}, "
                      "code=201)]), EndpointMethod(name='get', description='Returns all your "
                      "employees.', parameters=[EndpointParameter(name='company_id', "
                      "in_location='path', type='string', required=True, format='')], "
                      "request_schemas=[], response_schemas=[ContentSchema(name='EmployeeList', "
                      "content_type='application/json', definition={'title': 'Employee List', "
                      "'type': 'array', 'items': {'$ref': '#/components/schemas/Employee'}}, "
                      "code=200)])], _id=UUID('b4862b21-fb97-d435-8856-1712e8e5216a')), "
                      "EndpointLayer(path='/employees/{employee_num}', api_levels=['employees'], "
                      "parameters=[EndpointParameter(name='employee_num', in_location='path', "
                      "type='string', required=True, format='')], next=[], "
                      "methods=[EndpointMethod(name='get', description='Returns one of your company "
                      "employees', parameters=[EndpointParameter(name='company_id', "
                      "in_location='path', type='string', required=True, format=''), "
                      "EndpointParameter(name='employee_num', in_location='path', type='integer', "
                      "required=True, format='')], request_schemas=[], "
                      "response_schemas=[ContentSchema(name='Employee', "
                      "content_type='application/json', definition={'title': 'Employee', 'type': "
                      "'object', 'allOf': [{'$ref': '#/components/schemas/EmployeeBase'}]}, "
                      "code=200)])], _id=UUID('5487ce1e-af19-922a-d9b8-a714e61a441c'))], "
                      'next=APITree(branches=[]), '
                      "_id=UUID('17e0aa3c-0398-3ca8-ea7e-9d498c778ea6')), "
                      "APINode(api='departments', "
                      "layers=[EndpointLayer(path='/departments/{department_name}', "
                      "api_levels=['departments'], "
                      "parameters=[EndpointParameter(name='department_name', in_location='path', "
                      "type='string', required=True, format='')], next=[APINode(api='employees', "
                      "layers=[EndpointLayer(path='/employees', api_levels=['employees'], "
                      "parameters=[], next=[], methods=[EndpointMethod(name='post', "
                      "description='Hires a new employee!', "
                      "parameters=[EndpointParameter(name='company_id', in_location='path', "
                      "type='string', required=True, format='')], "
                      "request_schemas=[ContentSchema(name='EmployeeCreate', "
                      "content_type='application/json', definition={'title': 'Employee Create "
                      "Request', 'type': 'object', 'allOf': [{'$ref': "
                      "'#/components/schemas/EmployeeBase'}]}, code=0)], "
                      "response_schemas=[ContentSchema(name='Employee', "
                      "content_type='application/json', definition={'title': 'Employee', 'type': "
                      "'object', 'allOf': [{'$ref': '#/components/schemas/EmployeeBase'}]}, "
                      "code=201)]), EndpointMethod(name='get', description='Returns all your "
                      "employees.', parameters=[EndpointParameter(name='company_id', "
                      "in_location='path', type='string', required=True, format='')], "
                      "request_schemas=[], response_schemas=[ContentSchema(name='EmployeeList', "
                      "content_type='application/json', definition={'title': 'Employee List', "
                      "'type': 'array', 'items': {'$ref': '#/components/schemas/Employee'}}, "
                      "code=200)])], _id=UUID('b4862b21-fb97-d435-8856-1712e8e5216a')), "
                      "EndpointLayer(path='/employees/{employee_num}', api_levels=['employees'], "
                      "parameters=[EndpointParameter(name='employee_num', in_location='path', "
                      "type='string', required=True, format='')], next=[], "
                      "methods=[EndpointMethod(name='get', description='Returns one of your company "
                      "employees', parameters=[EndpointParameter(name='company_id', "
                      "in_location='path', type='string', required=True, format=''), "
                      "EndpointParameter(name='employee_num', in_location='path', type='integer', "
                      "required=True, format='')], request_schemas=[], "
                      "response_schemas=[ContentSchema(name='Employee', "
                      "content_type='application/json', definition={'title': 'Employee', 'type': "
                      "'object', 'allOf': [{'$ref': '#/components/schemas/EmployeeBase'}]}, "
                      "code=200)])], _id=UUID('5487ce1e-af19-922a-d9b8-a714e61a441c'))], "
                      'next=APITree(branches=[]), '
                      "_id=UUID('17e0aa3c-0398-3ca8-ea7e-9d498c778ea6'))], methods=[], "
                      "_id=UUID('8d723104-f773-83c1-3458-a748e9bb17bc'))], "
                      "next=APITree(branches=[APINode(api='employees', "
                      "layers=[EndpointLayer(path='/employees', api_levels=['employees'], "
                      "parameters=[], next=[], methods=[EndpointMethod(name='post', "
                      "description='Hires a new employee!', "
                      "parameters=[EndpointParameter(name='company_id', in_location='path', "
                      "type='string', required=True, format='')], "
                      "request_schemas=[ContentSchema(name='EmployeeCreate', "
                      "content_type='application/json', definition={'title': 'Employee Create "
                      "Request', 'type': 'object', 'allOf': [{'$ref': "
                      "'#/components/schemas/EmployeeBase'}]}, code=0)], "
                      "response_schemas=[ContentSchema(name='Employee', "
                      "content_type='application/json', definition={'title': 'Employee', 'type': "
                      "'object', 'allOf': [{'$ref': '#/components/schemas/EmployeeBase'}]}, "
                      "code=201)]), EndpointMethod(name='get', description='Returns all your "
                      "employees.', parameters=[EndpointParameter(name='company_id', "
                      "in_location='path', type='string', required=True, format='')], "
                      "request_schemas=[], response_schemas=[ContentSchema(name='EmployeeList', "
                      "content_type='application/json', definition={'title': 'Employee List', "
                      "'type': 'array', 'items': {'$ref': '#/components/schemas/Employee'}}, "
                      "code=200)])], _id=UUID('b4862b21-fb97-d435-8856-1712e8e5216a')), "
                      "EndpointLayer(path='/employees/{employee_num}', api_levels=['employees'], "
                      "parameters=[EndpointParameter(name='employee_num', in_location='path', "
                      "type='string', required=True, format='')], next=[], "
                      "methods=[EndpointMethod(name='get', description='Returns one of your company "
                      "employees', parameters=[EndpointParameter(name='company_id', "
                      "in_location='path', type='string', required=True, format=''), "
                      "EndpointParameter(name='employee_num', in_location='path', type='integer', "
                      "required=True, format='')], request_schemas=[], "
                      "response_schemas=[ContentSchema(name='Employee', "
                      "content_type='application/json', definition={'title': 'Employee', 'type': "
                      "'object', 'allOf': [{'$ref': '#/components/schemas/EmployeeBase'}]}, "
                      "code=200)])], _id=UUID('5487ce1e-af19-922a-d9b8-a714e61a441c'))], "
                      'next=APITree(branches=[]), '
                      "_id=UUID('17e0aa3c-0398-3ca8-ea7e-9d498c778ea6'))]), "
                      "_id=UUID('b5d32b16-6619-4cb1-d710-37d1b83e90ec'))]), "
                      "_id=UUID('eb2083e6-ce16-4dba-0ff1-8e0242af9fc3'))])")
